version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "klusoga"
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "klusoga"
    groups:
      actions:
        patterns:
          - "*"