# permissions for end users to view mssqltargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mssqltarget-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: klusoga-backup-operator
    app.kubernetes.io/part-of: klusoga-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: mssqltarget-viewer-role
rules:
- apiGroups:
  - klusoga.de
  resources:
  - mssqltargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - klusoga.de
  resources:
  - mssqltargets/status
  verbs:
  - get
