# permissions for end users to edit mssqltargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mssqltarget-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: klusoga-backup-operator
    app.kubernetes.io/part-of: klusoga-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: mssqltarget-editor-role
rules:
- apiGroups:
  - backup.klusoga.de
  resources:
  - mssqltargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.klusoga.de
  resources:
  - mssqltargets/status
  verbs:
  - get
