---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - klusoga.de
  resources:
  - destinations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klusoga.de
  resources:
  - destinations/finalizers
  verbs:
  - update
- apiGroups:
  - klusoga.de
  resources:
  - destinations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - klusoga.de
  resources:
  - mssqltargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klusoga.de
  resources:
  - mssqltargets/finalizers
  verbs:
  - update
- apiGroups:
  - klusoga.de
  resources:
  - mssqltargets/status
  verbs:
  - get
  - patch
  - update
