apiVersion: backup.klusoga.de/v1alpha1
kind: Destination
metadata:
  labels:
    app.kubernetes.io/name: destination
    app.kubernetes.io/instance: destination-sample
    app.kubernetes.io/part-of: klusoga-backup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: klusoga-backup-operator
  name: s3
spec:
  type: aws
  awsSpec:
    bucket: klusoga-backup
    region: eu-central-1
    secretRef: backup-bucket